name: Calculate
run-name: Calculate
on: [push]
jobs:
    calculate:
        name: calculate
        runs-on: ubuntu-latest
        steps:
        - name: Check out code
          uses: actions/checkout@v1
        - name: Setup Go
          uses: actions/setup-go@v1
          with:
            go-version: 1.22.5
        - name: Run
          run: go run main.go